
      - name: security test
        run: |
          docker run \
          --pull always \
          -e ACTIVE_CONFIG_FILE_PATH=${{ github.event.inputs.ACTIVE_CONFIG_FILE_PATH }} \
          -v $(pwd)/noname:/noname \
          us-central1-docker.pkg.dev/noname-docker-release/active-cli:$(curl -k ${{ github.event.inputs.ACTIVE_API_URL }}/backend/version) \
          scan \
          --api-url=${{ github.event.inputs.ACTIVE_API_URL }} \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} \
          --severity-threshold=${{ github.event.inputs.ACTIVE_SEVERITY_THRESHOLD }} \
          --test-group-id=${{ github.event.inputs.ACTIVE_TEST_GROUP_ID }} \
          --branch-name=${{ github.head_ref || github.ref_name }} \
          --network host

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello world
